# frozen_string_literal: true

source "https://rubygems.org"

gem "activerecord", "~> 8.0"
gem "pg", "~> 1.5"
gem "listen", "~> 3.9"
gem "rake", "~> 13.0"

group :test do
  gem "rspec", "~> 3.13"
  gem "simplecov", "~> 0.22"
  gem "sqlite3", "~> 2.6"
end
